In [1]:
!pip install undetected-chromedriver

Collecting undetected-chromedriver
  Downloading undetected-chromedriver-3.5.5.tar.gz (65 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting selenium>=4.9.0 (from undetected-chromedriver)
  Using cached selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from undetected-chromedriver) (2.32.5)
Collecting websockets (from undetected-chromedriver)
  Downloading websockets-16.0-cp310-cp310-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from selenium>=4.9.0->undetected-chromedriver) (2026.1.4)
Collecting trio<1.0,>=0.31.0 (from selenium>=4.9.0->undetected-chromedriver)
  Using cached trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium>=4.9.0->undetected-chromedriver)
  Using cached trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from selenium>=4.9.0->undetected-chromedriver) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected-chromedriver) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from selenium>=4.9.0->undetected-chromedriver) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (26.1.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: cffi>=1.14 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (2.0.0)
Requirement already satisfied: exceptiongroup in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (1.3.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver)
  Using cached wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected-chromedriver) (1.7.1)
Requirement already satisfied: pycparser in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\danish\miniconda3\envs\myenv\lib\site-packages (from requests->undetected-chromedriver) (3.4.4)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 381.0 kB/s eta 0:00:24
   -- ------------------------------------- 0.5/9.5 MB 381.0 kB/s eta 0:00:24
   -- ------------------------------------- 0.5/9.5 MB 381.0 kB/s eta 0:00:24
   --- ------------------------------------ 0.8/9.5 MB 353.1 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.5 MB 353.1 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.5 MB 353.1 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.5 MB 353.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.0/9.5 MB 347.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.0/9.5 MB 347.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.0/9.5 MB 347.1 kB/s eta 0:00:25
   ----- ---------------------------------- 1.3/9.5 MB 364.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.5 MB 364.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.5 MB 364.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.5 MB 364.7 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.5 MB 358.5 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.5 MB 358.5 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.5 MB 358.5 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.5 MB 362.1 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.5 MB 362.1 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.5 MB 362.1 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.5 MB 364.7 kB/s eta 0:00:21
   -------- ------------------------------- 2.1/9.5 MB 364.7 kB/s eta 0:00:21
   -------- ------------------------------- 2.1/9.5 MB 364.7 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.5 MB 370.8 kB/s eta 0:00:20
   --------- ------------------------------ 2.4/9.5 MB 370.8 kB/s eta 0:00:20
   ---------- ----------------------------- 2.6/9.5 MB 390.2 kB/s eta 0:00:18
   ---------- ----------------------------- 2.6/9.5 MB 390.2 kB/s eta 0:00:18
   ------------ --------------------------- 2.9/9.5 MB 394.7 kB/s eta 0:00:17
   ------------ --------------------------- 2.9/9.5 MB 394.7 kB/s eta 0:00:17
   ------------ --------------------------- 2.9/9.5 MB 394.7 kB/s eta 0:00:17
   ------------- -------------------------- 3.1/9.5 MB 397.7 kB/s eta 0:00:17
   ------------- -------------------------- 3.1/9.5 MB 397.7 kB/s eta 0:00:17
   ------------- -------------------------- 3.1/9.5 MB 397.7 kB/s eta 0:00:17
   -------------- ------------------------- 3.4/9.5 MB 397.1 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.5 MB 397.1 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.5 MB 397.1 kB/s eta 0:00:16
   --------------- ------------------------ 3.7/9.5 MB 404.6 kB/s eta 0:00:15
   --------------- ------------------------ 3.7/9.5 MB 404.6 kB/s eta 0:00:15
   ---------------- ----------------------- 3.9/9.5 MB 415.7 kB/s eta 0:00:14
   ---------------- ----------------------- 3.9/9.5 MB 415.7 kB/s eta 0:00:14
   ----------------- ---------------------- 4.2/9.5 MB 418.0 kB/s eta 0:00:13
   ----------------- ---------------------- 4.2/9.5 MB 418.0 kB/s eta 0:00:13
   ----------------- ---------------------- 4.2/9.5 MB 418.0 kB/s eta 0:00:13
   ------------------ --------------------- 4.5/9.5 MB 423.4 kB/s eta 0:00:12
   ------------------ --------------------- 4.5/9.5 MB 423.4 kB/s eta 0:00:12
   ------------------ --------------------- 4.5/9.5 MB 423.4 kB/s eta 0:00:12
   ------------------ --------------------- 4.5/9.5 MB 423.4 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.5 MB 413.4 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.5 MB 413.4 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.5 MB 413.4 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.5 MB 413.4 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.5 MB 413.4 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.5 MB 413.4 kB/s eta 0:00:12
   -------------------- ------------------- 5.0/9.5 MB 389.6 kB/s eta 0:00:12
   -------------------- ------------------- 5.0/9.5 MB 389.6 kB/s eta 0:00:12
   --------------------- ------------------ 5.2/9.5 MB 398.5 kB/s eta 0:00:11
   --------------------- ------------------ 5.2/9.5 MB 398.5 kB/s eta 0:00:11
   ----------------------- ---------------- 5.5/9.5 MB 409.2 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.5 MB 409.2 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.5 MB 409.2 kB/s eta 0:00:10
   ------------------------ --------------- 5.8/9.5 MB 406.8 kB/s eta 0:00:10
   ------------------------ --------------- 5.8/9.5 MB 406.8 kB/s eta 0:00:10
   ------------------------- -------------- 6.0/9.5 MB 410.1 kB/s eta 0:00:09
   ------------------------- -------------- 6.0/9.5 MB 410.1 kB/s eta 0:00:09
   -------------------------- ------------- 6.3/9.5 MB 415.8 kB/s eta 0:00:08
   -------------------------- ------------- 6.3/9.5 MB 415.8 kB/s eta 0:00:08
   --------------------------- ------------ 6.6/9.5 MB 419.0 kB/s eta 0:00:08
   --------------------------- ------------ 6.6/9.5 MB 419.0 kB/s eta 0:00:08
   --------------------------- ------------ 6.6/9.5 MB 419.0 kB/s eta 0:00:08
   ---------------------------- ----------- 6.8/9.5 MB 417.3 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.5 MB 417.3 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.5 MB 417.3 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.5 MB 417.3 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.5 MB 415.0 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.5 MB 415.0 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.5 MB 415.0 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.5 MB 416.7 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.5 MB 416.7 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.5 MB 416.7 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.5 MB 415.0 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.5 MB 415.0 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.5 MB 418.7 kB/s eta 0:00:04
   -------------------------------- ------- 7.9/9.5 MB 418.7 kB/s eta 0:00:04
   -------------------------------- ------- 7.9/9.5 MB 418.7 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.5 MB 419.1 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.5 MB 419.1 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.5 MB 419.1 kB/s eta 0:00:04
   ----------------------------------- ---- 8.4/9.5 MB 419.1 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.5 MB 419.1 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.5 MB 419.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 420.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 420.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 420.1 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 420.7 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 420.7 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 421.3 kB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 421.3 kB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 421.3 kB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 421.3 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 419.7 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 419.7 kB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 413.5 kB/s  0:00:23
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Using cached trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading websockets-16.0-cp310-cp310-win_amd64.whl (178 kB)
Building wheels for collected packages: undetected-chromedriver
  Building wheel for undetected-chromedriver (pyproject.toml): started
  Building wheel for undetected-chromedriver (pyproject.toml): finished with status 'done'
  Created wheel for undetected-chromedriver: filename=undetected_chromedriver-3.5.5-py3-none-any.whl size=47214 sha256=202adbfa05997f61858fc045d64ec45e32b323c079d78e9bebfc1d90325f9ceb
  Stored in directory: c:\users\danish\appdata\local\pip\cache\wheels\cf\a1\db\e1275b6f7259aacd6b045f8bfcb1fcbc93827a3916ba55d5b7
Successfully built undetected-chromedriver
Installing collected packages: sortedcontainers, wsproto, websockets, sniffio, outcome, trio, trio-websocket, selenium, undetected-chromedriver

   -------- ------------------------------- 2/9 [websockets]
   -------- ------------------------------- 2/9 [websockets]
   -------- ------------------------------- 2/9 [websockets]
   -------- ------------------------------- 2/9 [websockets]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   ---------------------- ----------------- 5/9 [trio]
   -------------------------- ------------- 6/9 [trio-websocket]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ------------------------------- -------- 7/9 [selenium]
   ----------------------------------- ---- 8/9 [undetected-chromedriver]
   ---------------------------------------- 9/9 [undetected-chromedriver]

Successfully installed outcome-1.3.0.post0 selenium-4.41.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 undetected-chromedriver-3.5.5 websockets-16.0 wsproto-1.3.2

In [3]:
import pandas as pd
import undetected_chromedriver as uc

from bs4 import BeautifulSoup

In [5]:
driver = uc.Chrome(version_main=146)

In [7]:
driver.get('https://fbref.com/en/comps/8/2023-2024/stats/2023-2024-Champions-League-Stats')

In [9]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 1.5 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/4.0 MB 1.7 MB/s eta 0:00:02
   ------------- -------------------------- 1.3/4.0 MB 1.7 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 1.5 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.5 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.5 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.5 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.4 MB/s  0:00:02
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [11]:
df = pd.read_html(driver.page_source, attrs={'id': "stats_squads_standard_for"})[0]

C:\Users\Danish\AppData\Local\Temp\ipykernel_18908\3706241889.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(driver.page_source, attrs={'id': "stats_squads_standard_for"})[0]

In [12]:
df.head()

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Squad               # Pl                Age
0          be Antwerp                 20               24.5
1         eng Arsenal                 23               25.2
2  es Atlético Madrid                 22               29.4
3        es Barcelona                 25               26.5
4    de Bayern Munich                 23               27.6

  Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                Poss           MP Starts   Min   90s         Gls Ast  ...
0               43.2            6     66   540   6.0           6   4  ...
1               56.5           10    110   930  10.3          19  16  ...
2               49.1           10    110   930  10.3          20  11  ...
3               54.2           10    110   900  10.0          19  18  ...
4               54.4           12    132  1080  12.0          21  16  ...

                          Per 90 Minutes
  G-PK PK PKatt CrdY CrdR            Gls   Ast   G+A  G-PK G+A-PK
0    6  0     1   15    2           1.00  0.67  1.67  1.00   1.67
1   18  1     1   13    0           1.84  1.55  3.39  1.74   3.29
2   20  0     1   25    1           1.94  1.06  3.00  1.94   3.00
3   19  0     0   30    2           1.90  1.80  3.70  1.90   3.70
4   18  3     3   15    1           1.75  1.33  3.08  1.50   2.83

[5 rows x 21 columns]

In [13]:
df.columns = ['_'.join(col).strip() for col in df.columns.values]

In [14]:
df.head()

,Unnamed: 0_level_0_Squad,Unnamed: 1_level_0_# Pl,Unnamed: 2_level_0_Age,Unnamed: 3_level_0_Poss,Playing Time_MP,Playing Time_Starts,Playing Time_Min,Playing Time_90s,Performance_Gls,Performance_Ast,...,Performance_G-PK,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK
0,be Antwerp,20,24.5,43.2,6,66,540,6.0,6,4,...,6,0,1,15,2,1.00,0.67,1.67,1.00,1.67
1,eng Arsenal,23,25.2,56.5,10,110,930,10.3,19,16,...,18,1,1,13,0,1.84,1.55,3.39,1.74,3.29
2,es Atlético Madrid,22,29.4,49.1,10,110,930,10.3,20,11,...,20,0,1,25,1,1.94,1.06,3.00,1.94,3.00
3,es Barcelona,25,26.5,54.2,10,110,900,10.0,19,18,...,19,0,0,30,2,1.90,1.80,3.70,1.90,3.70
4,de Bayern Munich,23,27.6,54.4,12,132,1080,12.0,21,16,...,18,3,3,15,1,1.75,1.33,3.08,1.50,2.83

In [16]:
player_stats = pd.read_html(driver.page_source, attrs={'id':"stats_standard"})[0]

C:\Users\Danish\AppData\Local\Temp\ipykernel_18908\4152174721.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_stats = pd.read_html(driver.page_source, attrs={'id':"stats_standard"})[0]

In [17]:
player_stats.head()

  Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk               Player             Nation
0                  1  Patrick van Aanholt             nl NED
1                  2     Brenden Aaronson             us USA
2                  3    Salis Abdul Samed             gh GHA
3                  4     Francesco Acerbi             it ITA
4                  5        Elias Achouri             tn TUN

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
                 Pos              Squad                Age               Born
0              DF,MF             nl PSV                 32               1990
1                 MF    de Union Berlin                 22               2000
2                 MF            fr Lens                 23               2000
3                 DF           it Inter                 35               1988
4              FW,MF   dk FC Copenhagen                 24               1999

  Playing Time              ... Performance                 Per 90 Minutes  \
            MP Starts  Min  ...          PK PKatt CrdY CrdR            Gls
0            2      1   99  ...           0     0    0    0           0.00
1            6      1  137  ...           0     0    0    0           0.00
2            6      6  495  ...           0     0    2    0           0.00
3            6      4  423  ...           0     0    1    0           0.00
4            8      7  552  ...           0     0    0    0           0.00

                           Unnamed: 24_level_0
    Ast   G+A  G-PK G+A-PK             Matches
0  0.00  0.00  0.00   0.00             Matches
1  0.00  0.00  0.00   0.00             Matches
2  0.00  0.00  0.00   0.00             Matches
3  0.21  0.21  0.00   0.21             Matches
4  0.16  0.16  0.00   0.16             Matches

[5 rows x 25 columns]